name: Build release apk

"on":
  workflow_dispatch:
    inputs:
      flutterChannel:
        description: "Flutter channel"
        default: stable
        required: true
        type: choice
        options:
          - stable
          - beta
          - master

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutterChannel }}

      - name: Decoding android/key.properties
        run: echo "${{ secrets.KEY_PROP }}" | base64 --decode > android/key.properties

      - name: Decoding android/key.jks
        run: echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/key.jks

      - name: Build fat apk
        run: |
          flutter pub get
          flutter build apk --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/app/outputs/apk/release/*.apk

      - name: Write summary
        run: |
          echo :blue_heart: Using **Flutter ${{ inputs.flutterChannel }}** >> $GITHUB_STEP_SUMMARY
