# Bundle the app to exe installer (usually no need to use this workflow)
name: Package installer (Inno setup)

"on":
  workflow_dispatch:
    inputs:
      flutterChannel:
        description: "Channel which Firebase will deploy into"
        default: stable
        required: true
        type: choice
        options:
          - master
          - beta
          - stable

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutterChannel }}

      - name: Flutter build for Windows
        run: |
          flutter pub get
          flutter build windows

      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "Inno\setup-script.iss"
        shell: cmd

      - name: Upload the installer as an artifact
        uses: actions/upload-artifact@v2
        with:
          path: "Inno/iiumschedulesetup.exe"
